# Generated by Django 4.2.20 on 2026-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='excluded_ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
